id: I6E90A0BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T07:27:36+00:00'
last_modified: '2022-06-08T01:07:09.072708+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5417
  title: སྨྱུང་བར་གནས་པའི་སྒྲུབ་ཐབས་དང་འབྲེལ་བའི་ཕན་ཡོན་དང་ཉམས་ཁྲིད་ཐེག་པ་མཆོག་གི་སྒོ་འབྱེད་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ECA6:
      image_group_id: I3CN5419
      title: ''
      total_pages: 267
      order: 1
      base_file: ECA6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
